HEAD:
  mixed-port: 7890
  socks-port: 7891
  allow-lan: true
  mode: rule
  log-level: info
  external-controller: :9090
  dns:
    enabled: true
    nameserver:
    - https://doh.pub/dns-query
    - https://223.5.5.5/dns-query
    - https://doh.360.cn/dns-query
    - https://dns.alidns.com/dns-query
    fallback:
    - 8.8.8.8
    - 8.8.4.4
    - tls://1.0.0.1:853
    - tls://dns.google:853
RULESET:
- - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - '[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com'
- - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - '[]DOMAIN-SUFFIX,services.googleapis.cn'
- - DIRECT
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
- - DIRECT
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
- - REJECT
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
- - REJECT
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
- - ğŸ† AdBlock
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
- - ğŸ† AdBlock
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
- - ğŸ† AdBlock
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
- - DIRECT
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
- - DIRECT
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
- - ğŸ“² Telegram
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
- - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
- - DIRECT
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
- - DIRECT
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
- - DIRECT
  - '[]GEOIP,CN,no-resolve'
- - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - '[]FINAL'
CUSTOM_PROXY_GROUP:
- name: "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
  type: select
- name: "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
  type: url-test
  url: "http://www.gstatic.com/generate_204"
  interval: 180
  tolerance: 50
- name: "ğŸ”¯ æ•…éšœè½¬ç§»"
  type: fallback
  url: "http://www.gstatic.com/generate_204"
  interval: 180
- name: "ğŸ”® è´Ÿè½½å‡è¡¡"
  type: load-balance
  url: "http://www.gstatic.com/generate_204"
  interval: 180
- name: "ğŸ“² Telegram"
  type: select
- name: "ğŸ† AdBlock"
  type: select
  proxies:
    - "REJECT"
    - "DIRECT"

